INSERT INTO TBL_USER
(USER_NUMBER, EMAIL, NAME, NICKNAME, PASSWORD)
VALUES(SEQ_USER.NEXTVAL, 'test12', 'teste1', 'teste33', '1234');





INSERT INTO TBL_ACHIEVEMENT
(ACHIEVEMENT_NUMBER, USER_NUMBER, MEDAL)
VALUES(SEQ_ACHIEVEMENT.NEXTVAL, 621, 'TESTMEDAL');


            SELECT SEQ_PROJECT.NEXTVAL FROM DUAL

        INSERT INTO TBL_PROJECT
        (PROJECT_NUMBER, TITLE, CATEGORY, CONTENT, AUTHENTICATION, START_DATE, END_DATE)
        VALUES(SEQ_PROJECT.NEXTVAL, #{title}, #{category}, #{content}, #{authentication}, #{startDate}, #{endDate})
        
        INSERT INTO TBL_PROJECT
(PROJECT_NUMBER, TITLE, CATEGORY, CONTENT, AUTHENTICATION)
VALUES(SEQ_PROJECT.NEXTVAL, 'test', 'test', 'test', 'teset');

SELECT PROJECT_NUMBER, TITLE, CATEGORY, CONTENT, AUTHENTICATION, START_DATE, END_DATE, STATUS
FROM TBL_PROJECT;

SELECT REPORT_NUMBER, USER_NUMBER, REVIEW_NUMBER, REASON
FROM TBL_REPORT;


SELECT REVIEW_NUMBER, USER_NUMBER
FROM TBL_LIKE;


SELECT REPORT_NUMBER, USER_NUMBER, REVIEW_NUMBER, REASON
FROM TBL_REPORT;

INSERT INTO TBL_LIKE
(REVIEW_NUMBER, USER_NUMBER)
VALUES(1, 1);

SELECT COUNT(USER_NUMBER) FROM TBL_LIKE WHERE REVIEW_NUMBER = 1;

INSERT INTO TBL_REVIEW
(REVIEW_NUMBER, USER_NUMBER, PROJECT_NUMBER, CONTENT, REGISTER_DATE)
VALUES(0, 0, 0, '', SYSDATE);


SELECT PROJECT_NUMBER, TITLE, CATEGORY, CONTENT, AUTHENTICATION, APPLY_COUNT, USER_NUMBER, START_DATE, END_DATE, STATUS
FROM TBL_PROJECT;

